[package]
name = "how_to_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = "0.7.4"
candid = "0.8.4"
ic-stable-memory = { path = "../../" }